// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.

import "dotenv/config";// This loads the .env file and makes the environment variables available in process.env 
import { defineConfig, env } from "prisma/config";


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
